repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-docstring-first

-   repo: https://github.com/rbubley/mirrors-prettier
    rev: 0.0.0
    hooks:
        - id: prettier
          args: ["--cache-location=.prettier_cache/cache"]

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 21.5b0
    hooks:
    - id: black-jupyter

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]

-   repo: https://github.com/deathbeds/prenotebook
    rev: f5bdb72a400f1a56fe88109936c83aa12cc349fa
    hooks:
    - id: prenotebook

-   repo: https://github.com/myint/rstcheck
    rev: 3f92957478422df87bd730abde66f089cc1ee19b
    hooks:
    -   id: rstcheck
